inherit_from: .rubocop_todo.yml

Layout/ArgumentAlignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
